spring.application.name=FirstProject
spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=Satish@1913
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
